import { ShoeItem } from "../intrefaces/shoeItem";
import { basicShoesList } from "./basicShoes";

const moment = require('moment');

export const init: ShoeItem[] = [
  {
    id: "1",
    shoe: basicShoesList[0],
    dateCreated: moment('2024-03-12T08:17:45.321Z'),
    datePurchased: undefined,
    size: 7.5,
  },
  {
    id: "2",
    shoe: basicShoesList[1],
    dateCreated: moment('2020-02-14'),
    datePurchased: moment('2026-02-14'),
    size: 4,
  },
  {
    id: "3",
    shoe: basicShoesList[2],
    dateCreated: moment('2023-11-05'),
    datePurchased: undefined,
    size: 5.5,
  },
  {
    id: "4",
    shoe: basicShoesList[3],
    dateCreated: moment('2024-01-19T'),
    datePurchased: undefined,
    size: 8,
  },
  {
    id: "5",
    shoe: basicShoesList[4],
    dateCreated: moment('2024-08-02'),
    datePurchased: undefined,
    size: 3.5,
  },
  {
    id: "6",
    shoe: basicShoesList[5],
    dateCreated: moment('2025-02-14'),
    datePurchased: undefined,
    size: 4.5,
  },
  {
    id: "7",
    shoe: basicShoesList[6],
    dateCreated: moment('2023-09-23T20:44:11.857Z'),
    datePurchased: undefined,
    size: 7,
  },
  {
    id: "8",
    shoe: basicShoesList[7],
    dateCreated: moment('2021-05-30'),
    datePurchased: undefined,
    size: 6.5,
  },
  {
    id: "9",
    shoe: basicShoesList[8],
    dateCreated: moment('2027-03-08'),
    datePurchased: undefined,
    size: 8.5,
  },

  // ----- Yeezy -----
  {
    id: "10",
    shoe: basicShoesList[9],
    dateCreated: moment('2021-12-11'),
    datePurchased: undefined,
    size: 5.5,
  },
  {
  
    id: "11",
    shoe: basicShoesList[10],
    dateCreated: moment('2030-10-07'),
    datePurchased: undefined,
    size: 4,
  },
  {
    id: "12",
    shoe: basicShoesList[11],
    dateCreated: moment('2025-06-27'),
    datePurchased: moment(),
    size: 7.5,
  },
  {
    id: "13",
    shoe: basicShoesList[12],
    dateCreated: moment('2024-02-18'),
    datePurchased: undefined,
    size: 3,
  },
  {
    id: "14",
    shoe: basicShoesList[13],
    dateCreated: moment('2023-11-30'),
    datePurchased: undefined,
    size: 8,
  },
  {
    id: "15",
    shoe: basicShoesList[14],
    dateCreated: moment('2025-01-05'),
    datePurchased: moment(),
    size: 5,
  },
  {
    id: "16",
    shoe: basicShoesList[15],
    dateCreated: moment('2024-07-14'),
    datePurchased: undefined,
    size: 6.5,
  },
  {
    id: "17",
    shoe: basicShoesList[16],
    dateCreated: moment('2023-09-19'),
    datePurchased: undefined,
    size: 4.5,
  },
  {
    id: "18",
    shoe: basicShoesList[17],
    dateCreated: moment('2025-04-22'),
    datePurchased: undefined,
    size: 7,
  },

  // ----- Nike & Jordan -----
  {
    id: "19",
    shoe: basicShoesList[18],
    dateCreated: moment('2024-06-03'),
    datePurchased: undefined,
    size: 5.5,
  },
  {
    id: "20",
    shoe: basicShoesList[19],
    dateCreated: moment('2023-12-15'),
    datePurchased: moment(),
    size: 6,
  },
  {
    id: "21",
    shoe: basicShoesList[20],
    dateCreated: moment('2025-02-28'),
    datePurchased: undefined,
    size: 8.5,
  },
  {
    id: "22",
    shoe: basicShoesList[21],
    dateCreated: moment('2024-09-09'),
    datePurchased: undefined,
    size: 3.5,
  },
  {
    id: "23",
    shoe: basicShoesList[22],
    dateCreated: moment('2023-10-21'),
    datePurchased: moment(),
    size: 7.5,
  },
  {
    id: "24",
    shoe: basicShoesList[23],
    dateCreated: moment('2025-05-12'),
    datePurchased: undefined,
    size: 4,
  },
  {
    id: "25",
    shoe: basicShoesList[24],
    dateCreated: moment('2024-11-01'),
    datePurchased: undefined,
    size: 5.5,
  },
  {
    id: "26",
    shoe: basicShoesList[25],
    dateCreated: moment('2023-09-30'),
    datePurchased: moment(),
    size: 6.5,
  },
  {
    id: "27",
    shoe: basicShoesList[26],
    dateCreated: moment('2025-07-04'),
    datePurchased: undefined,
    size: 7,
  },
  {
    id: "28",
    shoe: basicShoesList[27],
    dateCreated: moment('2024-04-16'),
    datePurchased: undefined,
    size: 8,
  },
  {
    id: "29",
    shoe: basicShoesList[28],
    dateCreated: moment('2023-11-18'),
    datePurchased: moment(),
    size: 3,
  },

  // ----- Nike + Off‑White -----
  {
    id: "30",
    shoe: basicShoesList[29],
    dateCreated: moment('2025-01-23'),
    datePurchased: undefined,
    size: 5,
  },
  {
    id: "31",
    shoe: basicShoesList[30],
    dateCreated: moment('2024-08-27'),
    datePurchased: undefined,
    size: 6,
  },
  {
    id: "32",
    shoe: basicShoesList[31],
    dateCreated: moment('2023-09-05'),
    datePurchased: moment(),
    size: 8.5,
  },
  {
    id: "33",
    shoe: basicShoesList[32],
    dateCreated: moment('2025-03-15'),
    datePurchased: undefined,
    size: 3.5,
  },
  {
    id: "34",
    shoe: basicShoesList[33],
    dateCreated: moment('2024-02-09'),
    datePurchased: undefined,
    size: 7.5,
  },

  // ----- Puma -----
  {
    id: "35",
    shoe: basicShoesList[34],
    dateCreated: moment('2023-10-28'),
    datePurchased: undefined,
    size: 4,
  },
  {
    id: "36",
    shoe: basicShoesList[35],
    dateCreated: moment('2025-06-11'),
    datePurchased: moment(),
    size: 5.5,
  },
];